// Connectors package - main exports
export * from './types';
export * from './base';

// Shopify connector exports
export {
  ShopifyConnector,
  ShopifyClient,
  syncOrders,
  syncProducts,
  syncCustomers,
  type ShopifyClientConfig,
  type ShopifyShop,
  type ShopifyOrder,
  type ShopifyProduct,
  type ShopifyCustomer,
  type ShopifyOrdersResponse,
  type ShopifyProductsResponse,
  type ShopifyCustomersResponse,
  type ShopifyLineItem,
  type ShopifyVariant,
  type ListOrdersParams as ShopifyListOrdersParams,
  type ListProductsParams as ShopifyListProductsParams,
  type ListCustomersParams as ShopifyListCustomersParams,
} from './shopify';

// Stripe connector exports
export {
  StripeConnector,
  StripeClient,
  syncStripeCustomers,
  syncStripePlans,
  syncStripeSubscriptions,
  syncStripeInvoices,
  processWebhookEvent,
  STRIPE_WEBHOOK_EVENTS,
  processCustomer as processStripeCustomer,
  processInvoice as processStripeInvoice,
  processSubscription as processStripeSubscription,
  processPlan as processStripePlan,
  getInternalCustomerId as getStripeInternalCustomerId,
  getInternalPlanId as getStripeInternalPlanId,
  getInternalSubscriptionId as getStripeInternalSubscriptionId,
  getInternalInvoiceId as getStripeInternalInvoiceId,
  deleteCustomerByExternalId as deleteStripeCustomer,
  deactivatePlan as deactivateStripePlan,
  cancelSubscription as cancelStripeSubscription,
  markInvoicePaid as markStripeInvoicePaid,
  markInvoiceVoid as markStripeInvoiceVoid,
  // Metrics
  calculateMRR,
  calculateARR,
  calculateMRRBreakdown,
  getSubscriptionMetrics,
  getCustomerMetrics,
  getRevenueForPeriod,
  type StripeClientConfig,
  type StripeListCustomersParams,
  type StripeListPricesParams,
  type StripeListSubscriptionsParams,
  type StripeListInvoicesParams,
  type WebhookProcessingResult,
  type MRRResult,
  type ARRResult,
  type SubscriptionMetrics,
  type CustomerMetrics,
  type Stripe,
} from './stripe';

// Webhook Gateway exports
export {
  // Gateway
  webhookGateway,
  WebhookGateway,
  type WebhookGatewayResult,
  // Types
  type WebhookProvider,
  type ParsedWebhookEvent,
  type WebhookVerifier,
  type WebhookEventProcessor,
  type VerificationResult,
  type WebhookGatewayConfig,
  DEFAULT_GATEWAY_CONFIG,
  // Verifiers
  getVerifier,
  isProviderSupported,
  getSupportedProviders,
  stripeVerifier,
  shopifyVerifier,
  // Processors
  getEventProcessor,
  getSupportedEvents,
  stripeProcessor,
  shopifyProcessor,
  STRIPE_SUPPORTED_EVENTS,
  SHOPIFY_SUPPORTED_EVENTS,
} from './webhooks';

// Real-time Data Pipeline exports
export {
  // Event Emitter
  realtimeEmitter,
  emitRealtimeEvent,
  subscribeToEvents,
  // Event Batch Processor
  EventBatchProcessor,
  // Metric Service
  metricService,
  triggerMetricRecalculation,
  // Anomaly Detector
  realtimeAnomalyDetector,
  // Types
  type RealtimeEventType,
  type RealtimeEvent,
  type MetricUpdateData,
  type AnomalyEventData,
  type EventCallback,
  type EventSubscription,
  type EventBatch,
  type BatchConfig,
  type MetricRecalculationRequest,
  type SSEConnection,
  DEFAULT_BATCH_CONFIG,
} from './realtime';

// GA4 Connector exports
export {
  GA4Connector,
  GA4Client,
  syncGA4Sessions,
  syncGA4Pageviews,
  syncGA4Events,
  syncGA4TrafficSources,
  syncGA4Channels,
  syncGA4UserAcquisition,
  syncGA4Conversions,
  GA4_CONVERSION_EVENTS,
  GA4_DIMENSIONS,
  GA4_METRICS,
  type GA4ClientConfig,
  type GA4Dimension,
  type GA4Metric,
  type GA4DateRange,
  type GA4FilterExpression,
  type GA4RunReportRequest,
  type GA4RunReportResponse,
  type GA4Row,
  type GA4OAuthConfig,
  type GA4TokenResponse,
  type GA4SyncOptions,
  type GA4DimensionName,
  type GA4MetricName,
} from './ga4';

// Meta Ads Connector exports
export {
  MetaAdsConnector,
  MetaAdsClient,
  syncMetaAdAccount,
  syncMetaCampaigns,
  syncMetaAdSets,
  syncMetaAds,
  syncMetaPerformance,
  META_ACCOUNT_STATUS,
  META_CAMPAIGN_OBJECTIVES,
  META_STATUS_MAP,
  type MetaAdsClientConfig,
  type MetaAdsOAuthConfig,
  type MetaAdsTokenResponse,
  type MetaAdsSyncOptions,
  type MetaApiResponse,
  type MetaAdAccount,
  type MetaCampaign,
  type MetaAdSet,
  type MetaAd,
  type MetaInsights,
  type MetaTargeting,
  type MetaAction,
} from './meta-ads';

// Google Ads Connector exports
export {
  GoogleAdsConnector,
  GoogleAdsClient,
  syncGoogleAdsAccount,
  syncGoogleAdsCampaigns,
  syncGoogleAdsAdGroups,
  syncGoogleAdsAds,
  syncGoogleAdsPerformance,
  syncGoogleAdsKeywords,
  GOOGLE_ADS_CAMPAIGN_STATUS,
  GOOGLE_ADS_AD_GROUP_STATUS,
  GOOGLE_ADS_AD_STATUS,
  GOOGLE_ADS_APPROVAL_STATUS,
  GOOGLE_ADS_CHANNEL_TYPE,
  GOOGLE_ADS_BIDDING_STRATEGY,
  GOOGLE_ADS_KEYWORD_MATCH_TYPE,
  type GoogleAdsClientConfig,
  type GoogleAdsOAuthConfig,
  type GoogleAdsTokenResponse,
  type GoogleAdsSyncOptions,
  type GoogleAdsSearchResponse,
  type GoogleAdsRow,
  type GoogleAdsCustomer,
  type GoogleAdsCampaign,
  type GoogleAdsCampaignBudget,
  type GoogleAdsAdGroup,
  type GoogleAdsAd,
  type GoogleAdsKeywordView,
  type GoogleAdsCriterion,
  type GoogleAdsMetrics,
  type GoogleAdsSegments,
} from './google-ads';

// Tiendanube Connector exports
export {
  TiendanubeConnector,
  TiendanubeClient,
  TIENDANUBE_SCOPES,
  syncTiendanubeCustomers,
  syncTiendanubeProducts,
  syncTiendanubeOrders,
  getTiendanubeInternalCustomerId,
  getTiendanubeInternalProductId,
  processTiendanubeCustomer,
  processTiendanubeProduct,
  processTiendanubeOrder,
  deleteTiendanubeProduct,
  cancelTiendanubeOrder,
  processTiendanubeWebhook,
  verifyTiendanubeWebhook,
  TIENDANUBE_WEBHOOK_EVENTS,
  getEventCategory as getTiendanubeEventCategory,
  isTiendanubeEventSupported,
  type TiendanubeCurrency,
  type TiendanubeCountry,
  type TiendanubeClientConfig,
  type TiendanubeOAuthConfig,
  type TiendanubeTokenResponse,
  type TiendanubeStore,
  type TiendanubeCustomer,
  type TiendanubeProduct,
  type TiendanubeOrder,
  type TiendanubeOrderStatus,
  type TiendanubePaymentStatus,
  type TiendanubeShippingStatus,
  type TiendanubeWebhookEvent,
  type TiendanubeWebhookPayload,
  type TiendanubeWebhook,
  type TiendanubeSyncOptions,
  type TiendanubeWebhookResult,
  type TiendanubeWebhookConfig,
} from './tiendanube';

// MercadoLibre Connector exports
export {
  MercadoLibreConnector,
  MercadoLibreClient,
  syncMercadoLibreListings,
  syncMercadoLibreOrders,
  syncMercadoLibreQuestions,
  getMercadoLibreInternalProductId,
  processMercadoLibreListing,
  processMercadoLibreOrder,
  processMercadoLibreQuestion,
  updateMercadoLibreListingStatus,
  calculateNetRevenue as calculateMercadoLibreNetRevenue,
  getQuestionStats as getMercadoLibreQuestionStats,
  getUrgentQuestions as getMercadoLibreUrgentQuestions,
  getShipmentDetails as getMercadoLibreShipmentDetails,
  syncShipmentStatus as syncMercadoLibreShipmentStatus,
  processShipmentWebhook as processMercadoLibreShipmentWebhook,
  getShippingStats as getMercadoLibreShippingStats,
  processMercadoLibreWebhook,
  verifyMercadoLibreWebhook,
  MERCADOLIBRE_WEBHOOK_TOPICS,
  isSupportedTopic as isMercadoLibreTopicSupported,
  getTopicCategory as getMercadoLibreTopicCategory,
  type MercadoLibreSiteId,
  type MercadoLibreCurrency,
  type MercadoLibreClientConfig,
  type MercadoLibreOAuthConfig,
  type MercadoLibreTokenResponse,
  type MercadoLibreUser,
  type MercadoLibreItem,
  type MercadoLibreOrder,
  type MercadoLibreOrderStatus,
  type MercadoLibreShipment,
  type MercadoLibreShipmentStatus,
  type MercadoLibreQuestion,
  type MercadoLibreNotification,
  type MercadoLibreWebhookTopic,
  type MercadoLibreSyncOptions,
  type MercadoLibreWebhookResult,
  type MercadoLibreWebhookConfig,
  type QuestionStats as MercadoLibreQuestionStats,
  type ShippingStats as MercadoLibreShippingStats,
  type ShippingStatusDetails as MercadoLibreShippingStatusDetails,
} from './mercadolibre';
